services:
  app_backend:
    build:
      context: ./backend/php
    container_name: backend_app
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
  app_frontend:
    build:
      context: ./frontend/nodejs
      dockerfile: Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend/src:/app
    ports:
      - "4200:4200"
    depends_on:
      - app_backend
    command: tail -f /dev/null
#    command: sleep infinity
  db:
    image: postgres:15
    container_name: laravel_pg
    environment:
      POSTGRES_DB: db_laravel
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
