services:
  app_laravel:
    build:
      context: ./backend
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend/laravel:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
  app_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    working_dir: /app
    volumes:
      - ./frontend/angular:/app
    ports:
      - "4200:4200"
    depends_on:
      - app_laravel
    command: tail -f /dev/null
#    command: sleep infinity
  db:
    image: postgres:15
    container_name: laravel_pg
    environment:
      POSTGRES_DB: db_laravel
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
