services:
  app_backend:
    build:
      context: ./backend/php
    container_name: backend_app
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_laravel
      DB_USERNAME: dba
      DB_PASSWORD: sys
    depends_on:
      - db
  app_frontend:
    build:
      context: ./frontend/nodejs
      dockerfile: Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend/src:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - app_backend
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_backend

  db:
    image: postgres:15
    container_name: laravel_pg
    environment:
      POSTGRES_DB: db_laravel
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
